name: bengkel_online_flutter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.20.2
  table_calendar: ^3.0.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  http: ^1.5.0
  image_picker: ^1.2.0
  flutter_svg: ^2.2.1
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^31.2.3
  syncfusion_flutter_datepicker: ^31.2.3
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  app_links: ^5.0.0
  shared_preferences: ^2.0.0
  connectivity_plus: ^6.0.5
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icons/
    - assets/svg/
    - assets/svg/logo.svg
    - assets/logo.png
    - assets/bg.png
    - assets/image/gambar_1.png
    - assets/image/gambar_2.png
    - assets/image/gambar_3.png
    - assets/icons/app_icon.png
    - assets/icons/logo_splash.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  test_api: ^0.7.7
